<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
// Facebook API
define('SOCIALSTREAMS_FB_CACHE_LIMIT', 60*60);
define('SOCIALSTREAMS_FB_PROFILE_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_FB_FRIENDS_CACHE_LIMIT', 60*60*24);
// Twitter API
define('SOCIALSTREAMS_TW_CACHE_LIMIT', 60*60);
define('SOCIALSTREAMS_TW_PROFILE_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_TW_FOLLOWERS_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_TW_COUNT', 20);
// LinkedIn API
define('SOCIALSTREAMS_LI_CACHE_LIMIT', 60*60);
define('SOCIALSTREAMS_LI_PROFILE_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_LI_CONNECTIONS_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_LI_COUNT', 20);
// LinkedIn API
define('SOCIALSTREAMS_GP_CACHE_LIMIT', 60*60);
define('SOCIALSTREAMS_GP_PROFILE_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_GP_CIRCLES_CACHE_LIMIT', 60*60*24);
define('SOCIALSTREAMS_GP_COUNT', 20);
?>
